/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

import Controlador.Conexion;
import Controlador.VoluntarioController;
import Modelo.Voluntario;
import java.sql.Connection;
import javax.swing.JOptionPane;

/**
 *
 * @author Judi
 */
public class BotonModificar extends javax.swing.JFrame {
    public Conexion conexion;
    public Connection link;

    /**
     * Creates new form BotonModificar
     */
    public BotonModificar() {
        initComponents();
        setLocationRelativeTo(null);
        conexion = new Conexion();
        link = conexion.Conectar();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblRut = new javax.swing.JLabel();
        txtRut = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        lblApellidoP = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        lblNombre = new javax.swing.JLabel();
        txtApellidoP = new javax.swing.JTextField();
        lblEdad = new javax.swing.JLabel();
        txtApellidoM = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        txtEdad = new javax.swing.JTextField();
        lblTelefono = new javax.swing.JLabel();
        txtTelefono = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtCorreo = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtProfesion = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtDebilidad = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtFortaleza = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtCalle = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtNumero = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtRegion = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtActivo = new javax.swing.JTextField();
        lblIdTarea = new javax.swing.JLabel();
        txtIdTarea = new javax.swing.JTextField();
        ModificarBttn = new javax.swing.JButton();
        lblMensaje = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 204), 20));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblRut.setText("Ingrese rut de persona a modificar:");
        jPanel1.add(lblRut, new org.netbeans.lib.awtextra.AbsoluteConstraints(88, 65, -1, -1));

        txtRut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRutActionPerformed(evt);
            }
        });
        jPanel1.add(txtRut, new org.netbeans.lib.awtextra.AbsoluteConstraints(289, 62, 187, -1));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Modificar Datos"));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblApellidoP.setText("Apellido Paterno:");
        jPanel2.add(lblApellidoP, new org.netbeans.lib.awtextra.AbsoluteConstraints(11, 68, 123, 22));
        jPanel2.add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 42, 156, 20));

        lblNombre.setText("Nombre:");
        jPanel2.add(lblNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 40, 59, 22));
        jPanel2.add(txtApellidoP, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 72, 156, 20));

        lblEdad.setText("Edad:");
        jPanel2.add(lblEdad, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 140, 41, 22));
        jPanel2.add(txtApellidoM, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 100, 140, 20));

        jLabel1.setText("ApellidoMaterno:");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, -1, -1));

        txtEdad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEdadActionPerformed(evt);
            }
        });
        jPanel2.add(txtEdad, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 140, 40, -1));

        lblTelefono.setText("Telefono:");
        jPanel2.add(lblTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 180, -1, -1));
        jPanel2.add(txtTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 180, 130, 20));

        jLabel2.setText("Correo:");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 220, -1, -1));
        jPanel2.add(txtCorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 220, 130, 20));

        jLabel3.setText("Profesion:");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 260, -1, -1));

        txtProfesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtProfesionActionPerformed(evt);
            }
        });
        jPanel2.add(txtProfesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 260, 130, 20));

        jLabel4.setText("Debilidad:");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 40, -1, -1));

        txtDebilidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDebilidadActionPerformed(evt);
            }
        });
        jPanel2.add(txtDebilidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 40, 140, 20));

        jLabel5.setText("Fortaleza:");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 70, -1, -1));

        txtFortaleza.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFortalezaActionPerformed(evt);
            }
        });
        jPanel2.add(txtFortaleza, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 70, 140, 20));

        jLabel6.setText("Calle:");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 100, -1, -1));
        jPanel2.add(txtCalle, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 100, 140, 20));

        jLabel7.setText("Numero:");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 130, -1, -1));
        jPanel2.add(txtNumero, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 130, 140, 20));

        jLabel8.setText("Region:");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 160, -1, -1));
        jPanel2.add(txtRegion, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 160, 90, -1));

        jLabel9.setText("Activo:");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 240, -1, -1));

        txtActivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtActivoActionPerformed(evt);
            }
        });
        jPanel2.add(txtActivo, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 240, 25, -1));

        lblIdTarea.setText("Id Tarea:");
        jPanel2.add(lblIdTarea, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 280, -1, -1));
        jPanel2.add(txtIdTarea, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 280, 27, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 110, 580, 320));

        ModificarBttn.setText("MODIFICAR");
        ModificarBttn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ModificarBttnActionPerformed(evt);
            }
        });
        jPanel1.add(ModificarBttn, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 60, -1, -1));
        jPanel1.add(lblMensaje, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 100, 150, 20));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 700, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 476, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtRutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRutActionPerformed
        
    }//GEN-LAST:event_txtRutActionPerformed

    private void txtEdadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEdadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEdadActionPerformed

    private void ModificarBttnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ModificarBttnActionPerformed
        MenuOpciones menuO = new MenuOpciones();
        if (modificarDatos())
        {
            JOptionPane.showMessageDialog(null,"EXITO");
        }
        else
        {
            JOptionPane.showMessageDialog(null,"FRACASO");
        }
        this.setVisible(false);
        menuO.setVisible(true);
    }//GEN-LAST:event_ModificarBttnActionPerformed

    private void txtActivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtActivoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtActivoActionPerformed

    private void txtDebilidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDebilidadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDebilidadActionPerformed

    private void txtProfesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtProfesionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtProfesionActionPerformed

    private void txtFortalezaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFortalezaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFortalezaActionPerformed

    private boolean modificarDatos()
    {
        VoluntarioController vc = new VoluntarioController();
        Voluntario voluntario = vc.Buscar(link, txtRut.getText());
        
        try
        {
            if(voluntario != null )
            {
                voluntario.setRut(txtRut.getText());
                voluntario.setNombre(txtNombre.getText());
                voluntario.setApellidoPaterno(txtApellidoP.getText());
                voluntario.setApellidoMaterno(txtApellidoM.getText());
                voluntario.setEdad(Integer.parseInt(txtEdad.getText()));
                voluntario.setTelefono(Integer.parseInt(txtTelefono.getText()));
                voluntario.setCorreo(txtCorreo.getText());
                voluntario.setProfesion(txtProfesion.getText());
                voluntario.setDebilidad(txtDebilidad.getText());
                voluntario.setFortaleza(txtFortaleza.getText());
                voluntario.setCalle(txtCalle.getText());
                voluntario.setNumeroCalle(Integer.parseInt(txtNumero.getText()));
                voluntario.setRegion(txtRegion.getText());
                voluntario.setActivo(Integer.parseInt(txtActivo.getText()));
                voluntario.setIdTarea(Integer.parseInt(txtIdTarea.getText()));

                vc.Actualizar(link, voluntario);
                JOptionPane.showMessageDialog(null,"SE ACTUALIZO");
                return true;
            }
            
        }catch(Exception e)
        {
            System.out.println("Error");
        }
        return false;
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BotonModificar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BotonModificar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BotonModificar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BotonModificar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BotonModificar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ModificarBttn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblApellidoP;
    private javax.swing.JLabel lblEdad;
    private javax.swing.JLabel lblIdTarea;
    private javax.swing.JLabel lblMensaje;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblRut;
    private javax.swing.JLabel lblTelefono;
    private javax.swing.JTextField txtActivo;
    private javax.swing.JTextField txtApellidoM;
    private javax.swing.JTextField txtApellidoP;
    private javax.swing.JTextField txtCalle;
    private javax.swing.JTextField txtCorreo;
    private javax.swing.JTextField txtDebilidad;
    private javax.swing.JTextField txtEdad;
    private javax.swing.JTextField txtFortaleza;
    private javax.swing.JTextField txtIdTarea;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtNumero;
    private javax.swing.JTextField txtProfesion;
    private javax.swing.JTextField txtRegion;
    private javax.swing.JTextField txtRut;
    private javax.swing.JTextField txtTelefono;
    // End of variables declaration//GEN-END:variables
}
