/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

import Controlador.Conexion;
import Controlador.VoluntarioController;
import Modelo.Voluntario;
import java.sql.Connection;

/**
 *
 * @author Judi
 */
public class BotonAgregar extends javax.swing.JFrame {
    
    public Conexion conexion;
    public Connection link;
    /**
     * Creates new form BotonAgregar
     */
    public BotonAgregar() {
        initComponents();
        setLocationRelativeTo(null);
        conexion = new Conexion();
        link = conexion.Conectar();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        lblApellidoP = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        lblNombre = new javax.swing.JLabel();
        txtApellidoP = new javax.swing.JTextField();
        lblEdad = new javax.swing.JLabel();
        txtApellidoM = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        txtEdad = new javax.swing.JTextField();
        lblTelefono = new javax.swing.JLabel();
        txtTelefono = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtCorreo = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtProfesion = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtDebilidad = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtFortaleza = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtCalle = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtNumero = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtRegion = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtActivo = new javax.swing.JTextField();
        txtRut = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        agregarBttn = new javax.swing.JButton();
        lblMensaje = new javax.swing.JLabel();
        lblIdTarea = new javax.swing.JLabel();
        txtIdTarea = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 204), 20));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblApellidoP.setText("Apellido Paterno:");
        jPanel2.add(lblApellidoP, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 140, 123, 22));
        jPanel2.add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 110, 130, -1));

        lblNombre.setText("Nombre:");
        jPanel2.add(lblNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 110, 59, 22));
        jPanel2.add(txtApellidoP, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 140, 130, -1));

        lblEdad.setText("Edad:");
        jPanel2.add(lblEdad, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 200, 30, 22));
        jPanel2.add(txtApellidoM, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 170, 130, -1));

        jLabel1.setText("ApellidoMaterno:");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 170, -1, -1));

        txtEdad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEdadActionPerformed(evt);
            }
        });
        jPanel2.add(txtEdad, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 200, 40, -1));

        lblTelefono.setText("Telefono:");
        jPanel2.add(lblTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 230, -1, -1));
        jPanel2.add(txtTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 230, 130, -1));

        jLabel2.setText("Correo:");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 260, -1, -1));
        jPanel2.add(txtCorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 260, 130, -1));

        jLabel3.setText("Profesion:");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 290, -1, -1));
        jPanel2.add(txtProfesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 290, 130, -1));

        jLabel4.setText("Debilidad:");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 80, -1, -1));
        jPanel2.add(txtDebilidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 80, 130, -1));

        jLabel5.setText("Fortaleza:");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 110, -1, -1));
        jPanel2.add(txtFortaleza, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 110, 130, -1));

        jLabel6.setText("Calle:");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 140, -1, -1));

        txtCalle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCalleActionPerformed(evt);
            }
        });
        jPanel2.add(txtCalle, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 140, 130, -1));

        jLabel7.setText("Numero:");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 170, -1, -1));
        jPanel2.add(txtNumero, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 170, 47, -1));

        jLabel8.setText("Region:");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 210, -1, -1));
        jPanel2.add(txtRegion, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 210, 120, -1));

        jLabel9.setText("Activo:");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 310, -1, -1));
        jPanel2.add(txtActivo, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 310, 30, -1));

        txtRut.setText("Rut:");
        jPanel2.add(txtRut, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 80, -1, -1));
        jPanel2.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 80, 130, -1));

        agregarBttn.setText("Agregar");
        agregarBttn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregarBttnActionPerformed(evt);
            }
        });
        jPanel2.add(agregarBttn, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 400, 170, 30));
        jPanel2.add(lblMensaje, new org.netbeans.lib.awtextra.AbsoluteConstraints(506, 432, 150, 20));

        lblIdTarea.setText("Id Tarea:");
        jPanel2.add(lblIdTarea, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 340, -1, -1));
        jPanel2.add(txtIdTarea, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 340, 30, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtEdadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEdadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEdadActionPerformed

    private void agregarBttnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregarBttnActionPerformed
        if (agregarDatos())
        {
            lblMensaje.setText("EXITO");
        }
        else
        {
            lblMensaje.setText("FRACASO");
        }
    }//GEN-LAST:event_agregarBttnActionPerformed

    private void txtCalleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCalleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCalleActionPerformed
    
    private boolean agregarDatos()
    {
        VoluntarioController vc = new VoluntarioController();
        Voluntario voluntario = new Voluntario();
        
        try
        {
            voluntario.setRut(txtRut.getText());
            voluntario.setNombre(txtNombre.getText());
            voluntario.setApellidoPaterno(txtApellidoP.getText());
            voluntario.setApellidoMaterno(txtApellidoM.getText());
            voluntario.setEdad(Integer.parseInt(txtEdad.getText()));
            voluntario.setTelefono(Integer.parseInt(txtTelefono.getText()));
            voluntario.setCorreo(txtCorreo.getText());
            voluntario.setProfesion(txtProfesion.getText());
            voluntario.setDebilidad(txtDebilidad.getText());
            voluntario.setFortaleza(txtFortaleza.getText());
            voluntario.setCalle(txtCalle.getText());
            voluntario.setNumeroCalle(Integer.parseInt(txtNumero.getText()));
            voluntario.setRegion(txtRegion.getText());
            voluntario.setActivo(Integer.parseInt(txtActivo.getText()));
            voluntario.setIdTarea(Integer.parseInt(lblIdTarea.getText()));

            vc.Crear(link, voluntario);
            return true;

        }catch(Exception e)
        {
            System.out.println("Error");
        }
        return false;
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BotonAgregar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BotonAgregar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BotonAgregar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BotonAgregar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BotonAgregar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton agregarBttn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel lblApellidoP;
    private javax.swing.JLabel lblEdad;
    private javax.swing.JLabel lblIdTarea;
    private javax.swing.JLabel lblMensaje;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblTelefono;
    private javax.swing.JTextField txtActivo;
    private javax.swing.JTextField txtApellidoM;
    private javax.swing.JTextField txtApellidoP;
    private javax.swing.JTextField txtCalle;
    private javax.swing.JTextField txtCorreo;
    private javax.swing.JTextField txtDebilidad;
    private javax.swing.JTextField txtEdad;
    private javax.swing.JTextField txtFortaleza;
    private javax.swing.JTextField txtIdTarea;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtNumero;
    private javax.swing.JTextField txtProfesion;
    private javax.swing.JTextField txtRegion;
    private javax.swing.JLabel txtRut;
    private javax.swing.JTextField txtTelefono;
    // End of variables declaration//GEN-END:variables
}
